In [3]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [4]:
df=pd.read_csv('C:\\Users\\acer\\Downloads\\heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [3]:
df.shape

(1025, 14)

In [4]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [5]:
df.drop(['oldpeak','slope','ca','thal'],axis=1,inplace=True) 
df.head()

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  target
0   52    1   0       125   212    0        1      168      0       0
1   53    1   0       140   203    1        0      155      1       0
2   70    1   0       145   174    0        1      125      1       0
3   61    1   0       148   203    0        1      161      0       0
4   62    0   0       138   294    1        1      106      0       0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   target    1025 non-null   int64
dtypes: int64(10)
memory usage: 80.2 KB

In [7]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,1.000000

In [9]:
%pip install pgmpy

Collecting pgmpy
  Downloading pgmpy-1.1.2-py3-none-any.whl.metadata (13 kB)
Collecting huggingface_hub>=0.23 (from pgmpy)
  Downloading huggingface_hub-1.28.0-py3-none-any.whl.metadata (16 kB)
Collecting networkx>=3.0 (from pgmpy)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: numpy>=2.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pgmpy) (2.5.2)
Requirement already satisfied: scipy>=1.10 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pgmpy) (1.18.0)
Requirement already satisfied: scikit-learn>=1.2 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pgmpy) (1.9.0)
Requirement already satisfied: pandas>=1.5 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pgmpy) (3.0.5)
Collecting statsmodels>=0.14.5 (from pgmpy)
  Downloading statsmodels-0.14.6-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: tqdm>=4.64 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pgmpy) (4.70.0)
Requirement already satisfied: pyparsing>=3.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pgmpy) (3.3.2)
Requirement already satisfied: joblib>=1.2 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pgmpy) (1.5.3)
Collecting opt_einsum>=3.3 (from pgmpy)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Collecting scikit-base>=0.12.4 (from pgmpy)
  Downloading scikit_base-1.1.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface_hub>=0.23->pgmpy) (8.4.2)
Collecting filelock>=3.10.0 (from huggingface_hub>=0.23->pgmpy)
  Downloading filelock-3.32.3-py3-none-any.whl.metadata (2.0 kB)
Collecting fsspec>=2023.5.0 (from huggingface_hub>=0.23->pgmpy)
  Downloading fsspec-2026.7.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.5.2 (from huggingface_hub>=0.23->pgmpy)
  Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface_hub>=0.23->pgmpy) (0.28.1)
Requirement already satisfied: packaging>=20.9 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface_hub>=0.23->pgmpy) (26.3)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface_hub>=0.23->pgmpy) (6.0.3)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface_hub>=0.23->pgmpy) (4.16.0)
Requirement already satisfied: colorama in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from click<9.0.0,>=8.4.2->huggingface_hub>=0.23->pgmpy) (0.4.6)
Requirement already satisfied: anyio in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (4.14.2)
Requirement already satisfied: certifi in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (2026.7.22)
Requirement already satisfied: httpcore==1.* in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (1.0.9)
Requirement already satisfied: idna in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (3.19)
Requirement already satisfied: h11>=0.16 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (0.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.5->pgmpy) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.5->pgmpy) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5->pgmpy) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn>=1.2->pgmpy) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn>=1.2->pgmpy) (3.6.0)
Collecting patsy>=0.5.6 (from statsmodels>=0.14.5->pgmpy)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Downloading pgmpy-1.1.2-py3-none-any.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   --------------------- ------------------ 1.3/2.4 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 8.3 MB/s  0:00:00
Downloading huggingface_hub-1.28.0-py3-none-any.whl (793 kB)
   ---------------------------------------- 0.0/793.2 kB ? eta -:--:--
   ---------------------------------------- 793.2/793.2 kB 7.0 MB/s  0:00:00
Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------------------------- -------------- 2.6/4.0 MB 12.2 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 11.2 MB/s  0:00:00
Downloading filelock-3.32.3-py3-none-any.whl (98 kB)
Downloading fsspec-2026.7.0-py3-none-any.whl (206 kB)
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 15.0 MB/s  0:00:00
Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading scikit_base-1.1.0-py3-none-any.whl (165 kB)
Downloading statsmodels-0.14.6-cp314-cp314-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ------- -------------------------------- 1.8/9.6 MB 9.3 MB/s eta 0:00:01
   ----------------- ---------------------- 4.2/9.6 MB 10.2 MB/s eta 0:00:01
   ------------------------- -------------- 6.0/9.6 MB 10.6 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 10.5 MB/s  0:00:00
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Installing collected packages: scikit-base, patsy, opt_einsum, networkx, hf-xet, fsspec, filelock, statsmodels, huggingface_hub, pgmpy

   ----------------------------------------  0/10 [scikit-base]
   ----------------------------------------  0/10 [scikit-base]
   ----------------------------------------  0/10 [scikit-base]
   ----------------------------------------  0/10 [scikit-base]
   ----------------------------------------  0/10 [scikit-base]
   ----------------------------------------  0/10 [scikit-base]
   ----------------------------------------  0/10 [scikit-base]
   ----------------------------------------  0/10 [scikit-base]
   ----------------------------------------  0/10 [scikit-base]
   ----------------------------------------  0/10 [scikit-base]
   ----------------------------------------  0/10 [scikit-base]
   ----------------------------------------  0/10 [scikit-base]
   ----------------------------------------  0/10 [scikit-base]
   ---- -----------------------------------  1/10 [patsy]
   ---- -----------------------------------  1/10 [patsy]
   ---- -----------------------------------  1/10 [patsy]
   ---- -----------------------------------  1/10 [patsy]
   ---- -----------------------------------  1/10 [patsy]
   ---- -----------------------------------  1/10 [patsy]
   ---- -----------------------------------  1/10 [patsy]
   -------- -------------------------------  2/10 [opt_einsum]
   -------- -------------------------------  2/10 [opt_einsum]
   -------- -------------------------------  2/10 [opt_einsum]
   -------- -------------------------------  2/10 [opt_einsum]
   -------- -------------------------------  2/10 [opt_einsum]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ------------ ---------------------------  3/10 [networkx]
   ---------------- -----------------------  4/10 [hf-xet]
   -------------------- -------------------  5/10 [fsspec]
   -------------------- -------------------  5/10 [fsspec]
   -------------------- -------------------  5/10 [fsspec]
   -------------------- -------------------  5/10 [fsspec]
   -------------------- -------------------  5/10 [fsspec]
   -------------------- -------------------  5/10 [fsspec]
   -------------------- -------------------  5/10 [fsspec]
   -------------------- -------------------  5/10 [fsspec]
   -------------------- -------------------  5/10 [fsspec]
   -------------------- -------------------  5/10 [fsspec]
   -------------------- -------------------  5/10 [fsspec]
   -------------------- -------------------  5/10 [fsspec]
   -------------------- -------------------  5/10 [fsspec]
   ------------------------ ---------------  6/10 [filelock]
   ------------------------ ---------------  6/10 [filelock]
   ------------------------ ---------------  6/10 [filelock]
   ------------------------ ---------------  6/10 [filelock]
   ------------------------ ---------------  6/10 [filelock]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]
   ---------------------------- -----------  7/10 [statsmodels]

In [11]:
%pip install --upgrade jupyter ipywidgets

Collecting jupyter
  Downloading jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting ipywidgets
  Downloading ipywidgets-8.1.9-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: notebook in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter) (7.6.2)
Collecting jupyter-console (from jupyter)
  Downloading jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: nbconvert in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter) (7.17.1)
Requirement already satisfied: ipykernel in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter) (7.3.0)
Requirement already satisfied: jupyterlab in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter) (4.6.3)
Requirement already satisfied: comm>=0.1.3 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipywidgets) (9.16.1)
Requirement already satisfied: traitlets>=4.3.1 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipywidgets) (5.16.1)
Collecting widgetsnbextension~=4.0.16 (from ipywidgets)
  Downloading widgetsnbextension-4.0.16-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.17 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.17-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.53)
Requirement already satisfied: psutil>=7 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.7)
Requirement already satisfied: executing>=1.2.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.2)
Requirement already satisfied: pure-eval in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipykernel->jupyter) (1.8.21)
Requirement already satisfied: jupyter-client>=8.9.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipykernel->jupyter) (8.9.1)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipykernel->jupyter) (5.9.1)
Requirement already satisfied: nest-asyncio2>=1.7.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipykernel->jupyter) (1.7.2)
Requirement already satisfied: packaging>=22 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipykernel->jupyter) (26.3)
Requirement already satisfied: pyzmq>=25 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipykernel->jupyter) (27.2.0)
Requirement already satisfied: tornado>=6.4.1 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from ipykernel->jupyter) (6.5.8)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-client>=8.9.0->ipykernel->jupyter) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=4.13.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-client>=8.9.0->ipykernel->jupyter) (4.16.0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel->jupyter) (4.11.3)
Requirement already satisfied: six>=1.5 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.9.0->ipykernel->jupyter) (1.17.0)
Requirement already satisfied: async-lru>=1.0.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab->jupyter) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-builder>=1.0.2 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab->jupyter) (1.2.2)
Requirement already satisfied: jupyter-lsp>=2.0.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab->jupyter) (2.3.1)
Requirement already satisfied: jupyter-server<3,>=2.19.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab->jupyter) (2.20.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab->jupyter) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: anyio in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.14.2)
Requirement already satisfied: certifi in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2026.7.22)
Requirement already satisfied: httpcore==1.* in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: idna in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (3.19)
Requirement already satisfied: h11>=0.16 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.5.4)
Requirement already satisfied: nbformat>=5.3.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (5.11.1)
Requirement already satisfied: prometheus-client>=0.9 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.26.0)
Requirement already satisfied: pywinpty!=3.0.4,>=2.0.1 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.0.5)
Requirement already satisfied: send2trash>=1.8.2 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.9.0)
Requirement already satisfied: babel>=2.10 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.15.0)
Requirement already satisfied: jsonschema>=4.18.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (4.26.0)
Requirement already satisfied: requests>=2.31 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.34.2)
Requirement already satisfied: argon2-cffi-bindings in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (26.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2026.6.3)
Requirement already satisfied: python-json-logger>=2.0.4 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (4.2.0)
Requirement already satisfied: pyyaml>=5.3 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (6.0.3)
Requirement already satisfied: rfc3339-validator in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: fqdn in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.1.0)
Requirement already satisfied: uri-template in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (25.10.0)
Requirement already satisfied: beautifulsoup4 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbconvert->jupyter) (4.15.0)
Requirement already satisfied: bleach!=5.0.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.4.0)
Requirement already satisfied: defusedxml in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbconvert->jupyter) (3.3.4)
Requirement already satisfied: nbclient>=0.5.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbconvert->jupyter) (0.11.0)
Requirement already satisfied: pandocfilters>=1.4.1 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.6.1)
Requirement already satisfied: tinycss2>=1.1.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.22.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.7.0)
Requirement already satisfied: lark>=1.2.2 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: cffi>=2 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.1.1)
Requirement already satisfied: pycparser in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from cffi>=2->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.0)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.9.2)
Requirement already satisfied: arrow>=0.15.0 in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.4.0)
Requirement already satisfied: tzdata in C:\Users\acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2026.3)
Downloading jupyter-1.1.1-py2.py3-none-any.whl (2.7 kB)
Downloading ipywidgets-8.1.9-py3-none-any.whl (140 kB)
Downloading jupyterlab_widgets-3.0.17-py3-none-any.whl (217 kB)
Downloading widgetsnbextension-4.0.16-py3-none-any.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ------------------------------------- -- 2.1/2.2 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 9.2 MB/s  0:00:00
Downloading jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Installing collected packages: widgetsnbextension, jupyterlab_widgets, ipywidgets, jupyter-console, jupyter

   ---------------------------------------- 0/5 [widgetsnbextension]
   -------- ------------------------------- 1/5 [jupyterlab_widgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ---------------- ----------------------- 2/5 [ipywidgets]
   ------------------------ --------------- 3/5 [jupyter-console]
   ------------------------ --------------- 3/5 [jupyter-console]
   ------------------------ --------------- 3/5 [jupyter-console]
   ---------------------------------------- 5/5 [jupyter]

Successfully installed ipywidgets-8.1.9 jupyter-1.1.1 jupyter-console-6.6.3 jupyterlab_widgets-3.0.17 widgetsnbextension-4.0.16
Note: you may need to restart the kernel to use updated packages.

In [7]:
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import BayesianEstimator

In [5]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='str')

In [11]:
model = DiscreteBayesianNetwork([
    ('age', 'target'), 
    ('sex', 'target'), 
    ('exang', 'target'), 
    ('cp', 'target'), 
    ('target', 'restecg'), 
    ('target', 'chol')
])
estimator = BayesianEstimator(model=model, data=df)
cpds = estimator.get_parameters(prior_type="BDeu", equivalent_sample_size=10)
model.add_cpds(*cpds)
print(model.get_cpds('age'))

C:\Users\acer\AppData\Local\Temp\ipykernel_19828\2874411499.py:9: FutureWarning: `pgmpy.estimators.BayesianEstimator` is deprecated and will be removed in v1.3.0. Please use `pgmpy.parameter_estimator.DiscreteBayesianEstimator` instead.
  estimator = BayesianEstimator(model=model, data=df)

+---------+------------+
| age(29) | 0.00410039 |
+---------+------------+
| age(34) | 0.00603276 |
+---------+------------+
| age(35) | 0.0147284  |
+---------+------------+
| age(37) | 0.00603276 |
+---------+------------+
| age(38) | 0.0118299  |
+---------+------------+
| age(39) | 0.0137622  |
+---------+------------+
| age(40) | 0.0108637  |
+---------+------------+
| age(41) | 0.0311535  |
+---------+------------+
| age(42) | 0.0253564  |
+---------+------------+
| age(43) | 0.0253564  |
+---------+------------+
| age(44) | 0.0350183  |
+---------+------------+
| age(45) | 0.0243902  |
+---------+------------+
| age(46) | 0.0224579  |
+---------+------------+
| age(47) | 0.017627   |
+---------+------------+
| age(48) | 0.0224579  |
+---------+------------+
| age(49) | 0.0166608  |
+---------+------------+
| age(50) | 0.0205255  |
+---------+------------+
| age(51) | 0.0379168  |
+---------+------------+
| age(52) | 0.0417815  |
+---------+------------+
| age(53) | 0.0253564  |
+---------+------------+
| age(54) | 0.0514434  |
+---------+------------+
| age(55) | 0.0292212  |
+---------+------------+
| age(56) | 0.0379168  |
+---------+------------+
| age(57) | 0.0553081  |
+---------+------------+
| age(58) | 0.0659361  |
+---------+------------+
| age(59) | 0.0446801  |
+---------+------------+
| age(60) | 0.0359844  |
+---------+------------+
| age(61) | 0.0301873  |
+---------+------------+
| age(62) | 0.0359844  |
+---------+------------+
| age(63) | 0.0311535  |
+---------+------------+
| age(64) | 0.0330859  |
+---------+------------+
| age(65) | 0.0263226  |
+---------+------------+
| age(66) | 0.0243902  |
+---------+------------+
| age(67) | 0.0301873  |
+---------+------------+
| age(68) | 0.0118299  |
+---------+------------+
| age(69) | 0.00893131 |
+---------+------------+
| age(70) | 0.0137622  |
+---------+------------+
| age(71) | 0.0108637  |
+---------+------------+
| age(74) | 0.00313421 |
+---------+------------+
| age(76) | 0.00313421 |
+---------+------------+
| age(77) | 0.00313421 |
+---------+------------+

In [12]:
print(model.get_cpds('sex'))

+--------+---------+
| sex(0) | 0.30628 |
+--------+---------+
| sex(1) | 0.69372 |
+--------+---------+

In [13]:
print(model.get_cpds('exang'))

+----------+----------+
| exang(0) | 0.661836 |
+----------+----------+
| exang(1) | 0.338164 |
+----------+----------+

In [14]:
print(model.get_cpds('chol'))

+-----------+-----------------------+-----------------------+
| target    | target(0)             | target(1)             |
+-----------+-----------------------+-----------------------+
| chol(126) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(131) | 0.006017648287385148  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(141) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(149) | 0.008001775271512138  | 0.007594905342452204  |
+-----------+-----------------------+-----------------------+
| chol(157) | 6.526733500417731e-05 | 0.007594905342452204  |
+-----------+-----------------------+-----------------------+
| chol(160) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(164) | 0.006017648287385148  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(166) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(167) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(168) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(169) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(172) | 0.006017648287385148  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(174) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(175) | 6.526733500417731e-05 | 0.0207775795420756    |
+-----------+-----------------------+-----------------------+
| chol(176) | 0.006017648287385148  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(177) | 0.0159382832080201    | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(178) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(180) | 6.526733500417731e-05 | 0.007594905342452204  |
+-----------+-----------------------+-----------------------+
| chol(182) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(183) | 6.526733500417731e-05 | 0.007594905342452204  |
+-----------+-----------------------+-----------------------+
| chol(184) | 0.006017648287385148  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(185) | 0.006017648287385148  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(186) | 6.526733500417731e-05 | 0.007594905342452204  |
+-----------+-----------------------+-----------------------+
| chol(187) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(188) | 0.013954156223893108  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(192) | 6.526733500417731e-05 | 0.013244622856576517  |
+-----------+-----------------------+-----------------------+
| chol(193) | 0.006017648287385148  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(195) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(196) | 6.526733500417731e-05 | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(197) | 0.011970029239766119  | 0.024544057884825145  |
+-----------+-----------------------+-----------------------+
| chol(198) | 0.008001775271512138  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(199) | 6.526733500417731e-05 | 0.01701110119932606   |
+-----------+-----------------------+-----------------------+
| chol(200) | 0.006017648287385148  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(201) | 6.526733500417731e-05 | 0.01701110119932606   |
+-----------+-----------------------+-----------------------+
| chol(203) | 0.0159382832080201    | 0.007594905342452204  |
+-----------+-----------------------+-----------------------+
| chol(204) | 0.0159382832080201    | 0.024544057884825145  |
+-----------+-----------------------+-----------------------+
| chol(205) | 0.008001775271512138  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(206) | 0.0159382832080201    | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(207) | 0.008001775271512138  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(208) | 6.526733500417731e-05 | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(209) | 6.526733500417731e-05 | 0.013244622856576517  |
+-----------+-----------------------+-----------------------+
| chol(210) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(211) | 6.526733500417731e-05 | 0.024544057884825145  |
+-----------+-----------------------+-----------------------+
| chol(212) | 0.02982717209690903   | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(213) | 6.526733500417731e-05 | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(214) | 6.526733500417731e-05 | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(215) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(216) | 0.006017648287385148  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(217) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(218) | 0.0159382832080201    | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(219) | 0.008001775271512138  | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(220) | 6.526733500417731e-05 | 0.022660818713450374  |
+-----------+-----------------------+-----------------------+
| chol(221) | 6.526733500417731e-05 | 0.013244622856576517  |
+-----------+-----------------------+-----------------------+
| chol(222) | 6.526733500417731e-05 | 0.013244622856576517  |
+-----------+-----------------------+-----------------------+
| chol(223) | 0.008001775271512138  | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(224) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(225) | 0.0159382832080201    | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(226) | 6.526733500417731e-05 | 0.024544057884825145  |
+-----------+-----------------------+-----------------------+
| chol(227) | 6.526733500417731e-05 | 0.015127862027951288  |
+-----------+-----------------------+-----------------------+
| chol(228) | 0.008001775271512138  | 0.007594905342452204  |
+-----------+-----------------------+-----------------------+
| chol(229) | 0.02387479114452806   | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(230) | 0.021890664160401068  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(231) | 0.013954156223893108  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(232) | 0.008001775271512138  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(233) | 0.006017648287385148  | 0.01701110119932606   |
+-----------+-----------------------+-----------------------+
| chol(234) | 0.0159382832080201    | 0.024544057884825145  |
+-----------+-----------------------+-----------------------+
| chol(235) | 6.526733500417731e-05 | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(236) | 0.006017648287385148  | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(237) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(239) | 0.013954156223893108  | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(240) | 6.526733500417731e-05 | 0.026427297056199915  |
+-----------+-----------------------+-----------------------+
| chol(241) | 0.006017648287385148  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(242) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(243) | 0.013954156223893108  | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(244) | 0.006017648287385148  | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(245) | 6.526733500417731e-05 | 0.01701110119932606   |
+-----------+-----------------------+-----------------------+
| chol(246) | 0.013954156223893108  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(247) | 0.006017648287385148  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(248) | 0.006017648287385148  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(249) | 0.021890664160401068  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(250) | 6.526733500417731e-05 | 0.01701110119932606   |
+-----------+-----------------------+-----------------------+
| chol(252) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(253) | 0.006017648287385148  | 0.007594905342452204  |
+-----------+-----------------------+-----------------------+
| chol(254) | 0.027843045112782037  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(255) | 0.006017648287385148  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(256) | 0.0159382832080201    | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(257) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(258) | 0.011970029239766119  | 0.007594905342452204  |
+-----------+-----------------------+-----------------------+
| chol(259) | 0.006017648287385148  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(260) | 0.008001775271512138  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(261) | 0.008001775271512138  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(262) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(263) | 0.008001775271512138  | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(264) | 0.006017648287385148  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(265) | 6.526733500417731e-05 | 0.013244622856576517  |
+-----------+-----------------------+-----------------------+
| chol(266) | 0.006017648287385148  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(267) | 0.006017648287385148  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(268) | 0.008001775271512138  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(269) | 0.013954156223893108  | 0.01701110119932606   |
+-----------+-----------------------+-----------------------+
| chol(270) | 0.006017648287385148  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(271) | 6.526733500417731e-05 | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(273) | 0.006017648287385148  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(274) | 0.017922410192147086  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(275) | 0.008001775271512138  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(276) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(277) | 6.526733500417731e-05 | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(278) | 6.526733500417731e-05 | 0.007594905342452204  |
+-----------+-----------------------+-----------------------+
| chol(281) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(282) | 0.027843045112782037  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(283) | 0.013954156223893108  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(284) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(286) | 0.0159382832080201    | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(288) | 0.0159382832080201    | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(289) | 0.0159382832080201    | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(290) | 0.006017648287385148  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(293) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(294) | 0.006017648287385148  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(295) | 6.526733500417731e-05 | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(298) | 0.006017648287385148  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(299) | 0.013954156223893108  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(300) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(302) | 6.526733500417731e-05 | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(303) | 6.526733500417731e-05 | 0.01701110119932606   |
+-----------+-----------------------+-----------------------+
| chol(304) | 0.006017648287385148  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(305) | 0.006017648287385148  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(306) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(307) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(308) | 6.526733500417731e-05 | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(309) | 0.013954156223893108  | 0.007594905342452204  |
+-----------+-----------------------+-----------------------+
| chol(311) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(313) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(315) | 0.008001775271512138  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(318) | 0.008001775271512138  | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(319) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(321) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(322) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(325) | 6.526733500417731e-05 | 0.011361383685201747  |
+-----------+-----------------------+-----------------------+
| chol(326) | 0.006017648287385148  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(327) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(330) | 0.0159382832080201    | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(335) | 0.0159382832080201    | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(340) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(341) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(342) | 6.526733500417731e-05 | 0.007594905342452204  |
+-----------+-----------------------+-----------------------+
| chol(353) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(354) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(360) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(394) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(407) | 0.008001775271512138  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(409) | 0.006017648287385148  | 6.194865695311747e-05 |
+-----------+-----------------------+-----------------------+
| chol(417) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+
| chol(564) | 6.526733500417731e-05 | 0.0057116661710774315 |
+-----------+-----------------------+-----------------------+